mdl = nn.Sequential()
mdl:add(nn.TemporalConvolution(26,64,4,2))
mdl:add(nn.ReLU())
mdl:add(nn.TemporalConvolution(64,128,4,2))
mdl:add(nn.ReLU())
mdl:add(nn.TemporalConvolution(128,128,4,2))
mdl:add(nn.ReLU())
mdl:add(nn.View(256))
-- mdl:add(nn.Dropout(0.5))
mdl:add(nn.Linear(256,256))
mdl:add(nn.ReLU())
-- mdl:add(nn.Dropout(0.5))
mdl:add(nn.Linear(256,256))
mdl:add(nn.ReLU())
mdl:add(nn.Linear(256,16))
mdl:add(nn.LogSoftMax())
mdl:cuda()

-- mdl = nn.Sequential()
-- mdl:add(nn.TemporalConvolution(1,128,8,4))
-- mdl:add(nn.ReLU())
-- mdl:add(nn.TemporalConvolution(128,128,8,4))
-- mdl:add(nn.ReLU())
-- mdl:add(nn.TemporalConvolution(128,256,8,4))
-- mdl:add(nn.ReLU())
-- mdl:add(nn.TemporalMaxPooling(12))
-- featuresOut = 8*4*256
-- mdl:add(nn.View(featuresOut))
-- mdl:add(nn.Linear(featuresOut,3000))
-- mdl:add(nn.ReLU())
-- mdl:add(nn.Linear(3000,16))
-- mdl:add(nn.LogSoftMax())
-- mdl:cuda()

-- mdl = nn.Sequential()
-- mdl:add(nn.TemporalConvolution(26,26,4,2))
-- mdl:add(nn.ReLU())
-- mdl:add(nn.TemporalConvolution(26,26,4,2))
-- mdl:add(nn.ReLU())
-- mdl:add(nn.TemporalConvolution(26,26,4,2))
-- mdl:add(nn.ReLU())
-- -- mdl:add(nn.TemporalMaxPooling(2))
-- mdl:add(nn.View(2*26))
-- mdl:add(nn.Linear(2*26,2*26))
-- mdl:add(nn.ReLU())
-- mdl:add(nn.Linear(2*26,17))
-- mdl:add(nn.LogSoftMax())
-- mdl:cuda()