mdl = nn.Sequential()
mdl:add(nn.TemporalConvolution(26,26,4,2))
mdl:add(nn.ReLU())
mdl:add(nn.TemporalConvolution(26,26,4,2))
mdl:add(nn.ReLU())
mdl:add(nn.TemporalConvolution(26,26,4,2))
mdl:add(nn.ReLU())
-- mdl:add(nn.TemporalMaxPooling(2))
mdl:add(nn.View(2*26))
mdl:add(nn.Linear(2*26,2*26))
mdl:add(nn.ReLU())
mdl:add(nn.Linear(2*26,17))
mdl:add(nn.LogSoftMax())
mdl:cuda()